### PR TITLE
Update to use latest npm CLI release

### PR DESCRIPTION
**Pull request by feelepxyz**
The new version has provenance support built in.

https://github.com/npm/cli/pull/6163

### CODE REVIEW

**Comment by feelepxyz** [comment]
cc @gr2m

**Review by gr2m — APPROVED** [review]
Thanks!

**Comment by gr2m** [comment]
no idea what this CI error is now, and I don't have the time to look into it right now

**Comment by feelepxyz** [comment]
> no idea what this CI error is now, and I don't have the time to look into it right now

fwiw the test failures look unrelated to this change and also on master: https://github.com/gr2m/semantic-release-plugin-npm-oidc/actions/runs/4286424841/jobs/7465976050

**Comment by gr2m** [comment]
`@semantic-release/npm` has support for provenance now: https://github.com/semantic-release/npm#npm-provenance

**Pull request closed without merging**
